import type { Locale } from './i18n'

export const UI_COPY = {
  th: {
    wordOfTheDay: 'คำสแลงประจำวัน',
    meaning: 'ความหมาย',
    example: 'ตัวอย่างประโยค',
    popularSlangs: 'คำสแลงล่าสุด',
    trendingTags: 'แท็กยอดนิยม',
    relatedWords: 'คำที่เกี่ยวข้อง',
    entries: 'รายการ',
    entry: 'รายการ',
    noEntries: 'ยังไม่มีคำสแลงในพจนานุกรม',
    origin: 'ที่มา',
    sources: 'แหล่งอ้างอิง',
    pronunciationSources: 'แหล่งอ้างอิงการออกเสียง',
    meaningSources: 'แหล่งอ้างอิงความหมาย',
    originSources: 'แหล่งอ้างอิงที่มา',
    usageSources: 'แหล่งอ้างอิงการใช้คำ',
    editorialExample: 'ตัวอย่างที่เรียบเรียงโดย Slangdee',
    sourcedExample: 'ตัวอย่างจากแหล่งอ้างอิง',
    originUnknown: 'ยังไม่ทราบที่มาที่แน่ชัด',
    originUncertain: 'ที่มายังไม่ยืนยัน',
    pendingReview: 'รอตรวจสอบแหล่งอ้างอิง เนื้อหาและที่มายังไม่ได้รับการยืนยัน',
    pendingReviewShort: 'รอตรวจสอบแหล่งอ้างอิง',
    reviewed: 'ตรวจสอบแหล่งอ้างอิงเมื่อ',
    revision: 'ฉบับแก้ไข',
    accessed: 'เข้าถึงเมื่อ',
    searchTitle: 'ผลการค้นหา',
    searchPrompt: 'พิมพ์คำสแลงในช่องค้นหาด้านบนเพื่อเริ่มค้นหา',
    noSearchResults: 'ไม่พบคำสแลงที่ตรงกับคำค้นหา',
    query: 'คำค้นหา: ',
    type: 'ประเภท',
  },
  en: {
    wordOfTheDay: 'Word of the day',
    meaning: 'Meaning',
    example: 'Example sentence',
    popularSlangs: 'Latest slangs',
    trendingTags: 'Trending tags',
    relatedWords: 'Related words',
    entries: 'entries',
    entry: 'entry',
    noEntries: 'There are no slang entries yet.',
    origin: 'Origin',
    sources: 'Sources',
    pronunciationSources: 'Pronunciation references',
    meaningSources: 'Meaning references',
    originSources: 'Origin references',
    usageSources: 'Usage references',
    editorialExample: 'Editorial example by Slangdee',
    sourcedExample: 'Example from a source',
    originUnknown: 'The origin is not established.',
    originUncertain: 'Origin not verified',
    pendingReview: 'Awaiting source review. This content and its origin have not been verified.',
    pendingReviewShort: 'Awaiting source review',
    reviewed: 'Sources reviewed on',
    revision: 'Revision',
    accessed: 'Accessed on',
    searchTitle: 'Search results',
    searchPrompt: 'Type a slang word in the search box above to start searching.',
    noSearchResults: 'No slang entries match your search.',
    query: 'Query: ',
    type: 'Type',
  },
} satisfies Record<Locale, Record<string, string>>

export function getCopy(locale: Locale) {
  return UI_COPY[locale]
}
