export interface BaseEntry {
  slug: string
  headword: string
  romanization: string
  ipa?: string
  englishWord: string
  englishMeaning: string
  thaiMeaning: string
  origin: string
  tags: string[]
}

/** Curated starter vocabulary for the bilingual directory. */
export const BASE_ENTRIES: BaseEntry[] = [
  { slug: 'chao-net', headword: 'ชาวเน็ต', romanization: 'chao-net', ipa: 'tɕʰāːw nē.t', englishWord: 'Netizens', englishMeaning: 'People who discuss and express opinions online.', thaiMeaning: 'ผู้คนที่ใช้และแสดงความคิดเห็นผ่านอินเทอร์เน็ต', origin: 'A compound of ชาว (people) and เน็ต (internet).', tags: ['internet-culture'] },
  { slug: 'gik', headword: 'กิ๊ก', romanization: 'gik', ipa: 'kík', englishWord: 'Side relationship', englishMeaning: 'A romantic or sexual relationship outside an official partnership.', thaiMeaning: 'คนที่คบหาหรือมีความสัมพันธ์เกินเพื่อน แต่ไม่ใช่แฟนอย่างเป็นทางการ', origin: 'Often explained as a playful shortening related to กุ๊กกิ๊ก.', tags: ['relationships'] },
  { slug: 'khu-jin', headword: 'คู่จิ้น', romanization: 'khu-jin', ipa: 'kʰûː tɕîn', englishWord: 'Imagined couple', englishMeaning: 'Two people whom fans imagine or ship as a romantic couple.', thaiMeaning: 'คู่คนดังที่แฟน ๆ จับคู่หรือจินตนาการให้เป็นคู่รัก', origin: 'คู่ means couple; จิ้น is a slang form associated with imagining a relationship.', tags: ['internet-culture'] },
  { slug: 'nok', headword: 'นก', romanization: 'nok', ipa: 'nók', englishWord: 'To miss out', englishMeaning: 'To fail romantically or miss the chance to be with someone.', thaiMeaning: 'พลาดหวังในความรักหรือชอบใครแล้วไม่สมหวัง', origin: 'A bird can fly away, so the chance is compared to something flying out of reach.', tags: ['relationships'] },
  { slug: 'the', headword: 'เท', romanization: 'the', ipa: 'tʰēː', englishWord: 'To dump', englishMeaning: 'To reject, abandon, or break up with someone.', thaiMeaning: 'ทิ้งหรือบอกเลิกใครสักคน', origin: 'Shortened from เททิ้ง, literally to pour or throw away.', tags: ['relationships'] },
  { slug: 'phueak', headword: 'เผือก', romanization: 'phueak', ipa: 'pʰɯ̀ːak', englishWord: 'Nosy', englishMeaning: 'To pry into other people’s business; nosy.', thaiMeaning: 'สอดรู้สอดเห็นหรืออยากรู้เรื่องของคนอื่น', origin: 'A softened spelling associated with the ruder เสือก.', tags: ['internet-culture'] },
  { slug: 'lao-lue', headword: 'เล้าหลือ', romanization: 'lao-lue', ipa: 'lǎw lʉ̌ː', englishWord: 'Pushy', englishMeaning: 'To pester or keep pressing someone.', thaiMeaning: 'ตื๊อ รบเร้า หรือกวนใจซ้ำ ๆ', origin: 'Colloquial slang with no single confirmed origin.', tags: ['internet-culture'] },
  { slug: 'yaom-jai', headword: 'ยอมใจ', romanization: 'yaom-jai', ipa: 'jɔ̄ːm tɕāj', englishWord: 'I give up / respect', englishMeaning: 'An admiring way to concede that someone or something is impressive.', thaiMeaning: 'ยอมรับในความเก่งหรือความสุดของใครบางคน', origin: 'A compound of ยอม (surrender) and ใจ (heart).', tags: ['compliments'] },
  { slug: 'khing', headword: 'ขิง', romanization: 'khing', ipa: 'kʰǐŋ', englishWord: 'To flex', englishMeaning: 'To show off or boast.', thaiMeaning: 'อวดหรือคุยโวความเก่งของตัวเอง', origin: 'A playful spoonerism associated with older expressions about boasting.', tags: ['internet-culture'] },
  { slug: 'uai', headword: 'อวย', romanization: 'uai', ipa: 'ʔūaj', englishWord: 'To hype', englishMeaning: 'To praise or promote someone or something enthusiastically, sometimes excessively.', thaiMeaning: 'ชมเชยหรือเชียร์ใครหรือสิ่งใดเกินจริง', origin: 'A colloquial re-use of อวย with an exaggerated praise meaning.', tags: ['internet-culture'] },
  { slug: 'aeo', headword: 'แอ๊ว', romanization: 'aeo', ipa: 'ʔɛ́ːw', englishWord: 'To flirt', englishMeaning: 'To charm or flirt with someone, usually a potential romantic interest.', thaiMeaning: 'โปรยเสน่ห์หรือจีบคนที่สนใจ', origin: 'Colloquial slang used in flirtatious contexts.', tags: ['relationships'] },
  { slug: 'po-taek', headword: 'โป๊ะแตก', romanization: 'po-taek', ipa: 'pōʔ tɛ̀ːk', englishWord: 'Secret exposed', englishMeaning: 'A hidden truth or embarrassing secret has been revealed.', thaiMeaning: 'ความลับหรือเรื่องที่ปิดไว้ถูกเปิดเผย', origin: 'Named after the seafood soup โป๊ะแตก, imagining its contents spilling out.', tags: ['internet-culture'] },
  { slug: 'mong-raeng', headword: 'มองแรง', romanization: 'mong-raeng', ipa: 'mɔ̄ːŋ rɛ̄ːŋ', englishWord: 'Give a dirty look', englishMeaning: 'To stare at someone intensely to show disapproval.', thaiMeaning: 'จ้องหรือมองอีกฝ่ายอย่างไม่พอใจ', origin: 'A literal phrase whose slang use emphasizes an angry look.', tags: ['internet-culture'] },
  { slug: 'i-i', headword: 'อิอิ', romanization: 'i-i', ipa: 'ʔìʔì', englishWord: 'Hehe', englishMeaning: 'A cute or soft giggle used in chat.', thaiMeaning: 'เสียงหัวเราะเบา ๆ แบบน่ารักในแชต', origin: 'Onomatopoeic text laughter common in messages and social media.', tags: ['chat'] },
  { slug: 'aep', headword: 'แอ๊บ', romanization: 'aep', ipa: 'ʔɛ́p', englishWord: 'Pretend', englishMeaning: 'To put on an act, especially to act cuter or more innocent than reality.', thaiMeaning: 'แกล้งทำหรือเสแสร้ง โดยเฉพาะทำเป็นน่ารักหรือไร้เดียงสา', origin: 'Shortened from the older expression แอ๊บแบ๊ว.', tags: ['internet-culture'] },
  { slug: 'noid', headword: 'นอยด์', romanization: 'noid', ipa: 'nɔ́ːj', englishWord: 'Anxious / overthinking', englishMeaning: 'To feel anxious, worried, or stuck overthinking.', thaiMeaning: 'กังวล คิดมาก หรือระแวงจนไม่สบายใจ', origin: 'Borrowed from the “-noid” sound in paranoid.', tags: ['emotions'] },
  { slug: 'mano', headword: 'มโน', romanization: 'mano', ipa: 'máʔ nōː', englishWord: 'To imagine', englishMeaning: 'To fantasize or make up a scenario in one’s head.', thaiMeaning: 'จินตนาการหรือคิดไปเองโดยไม่ตรงกับความจริง', origin: 'A formal word meaning mind that gained a teasing slang use.', tags: ['relationships'] },
  { slug: 'lam-yai', headword: 'ลำไย', romanization: 'lam-yai', ipa: 'lam.jāːj', englishWord: 'Annoying', englishMeaning: 'Annoying, especially through repetitive talk or behavior.', thaiMeaning: 'น่ารำคาญ โดยเฉพาะการพูดหรือทำซ้ำ ๆ', origin: 'A playful re-use of the fruit name, associated with several “annoyance” words.', tags: ['internet-culture'] },
  { slug: 'kao-lao', headword: 'เกาเหลา', romanization: 'kao-lao', ipa: 'kāw lǎw', englishWord: 'Not getting along', englishMeaning: 'To be on bad terms or have a feud with someone.', thaiMeaning: 'ไม่ถูกกันหรือมีเรื่องบาดหมางกัน', origin: 'A pun on ไม่กินเส้น (not eating noodles), since เกาเหลา is served without noodles.', tags: ['relationships'] },
  { slug: 'hua-ron', headword: 'หัวร้อน', romanization: 'hua-ron', ipa: 'hǔa rɔ́ːn', englishWord: 'Hot-headed', englishMeaning: 'Quick to anger or visibly furious.', thaiMeaning: 'โมโหง่ายหรือกำลังหัวเสียมาก', origin: 'A Thai rendering of the idea of being hot-headed.', tags: ['emotions'] },
  { slug: 'pang', headword: 'ปัง', romanization: 'pang', ipa: 'paŋ', englishWord: 'Stunning / a hit', englishMeaning: 'Outstanding, impressive, or highly successful.', thaiMeaning: 'โดดเด่น ปังมาก หรือประสบความสำเร็จอย่างเห็นได้ชัด', origin: 'Linked to the sound of striking a table; also associated with เป๊ะ and อลังการ.', tags: ['compliments'] },
  { slug: 'tamutami', headword: 'ตะมุตะมิ', romanization: 'tamutami', ipa: 'tàʔ múʔ tàʔ míʔ', englishWord: 'Adorably cute', englishMeaning: 'Cute in a soft, delicate, or overly adorable way.', thaiMeaning: 'น่ารักแบบจุ๋มจิ๋มและน่าเอ็นดู', origin: 'Playful sound-based slang with no confirmed single origin.', tags: ['compliments'] },
  { slug: 'chiu', headword: 'ชิว', romanization: 'chiu', ipa: 'tɕʰīw', englishWord: 'Chill', englishMeaning: 'Relaxed, easygoing, or taking it easy.', thaiMeaning: 'สบาย ๆ ผ่อนคลาย ไม่เคร่งเครียด', origin: 'Borrowed from English “chill out.”', tags: ['emotions'] },
  { slug: 'kak', headword: 'กาก', romanization: 'kak', ipa: 'kàːk', englishWord: 'Low-quality', englishMeaning: 'Poor, weak, or noticeably low quality.', thaiMeaning: 'คุณภาพต่ำ ห่วย หรือไม่เก่ง', origin: 'A literal word for residue that gained a quality judgment as slang.', tags: ['internet-culture'] },
  { slug: 'ngan-di', headword: 'งานดี', romanization: 'ngan-di', ipa: 'ŋāːn dīː', englishWord: 'Very good-looking', englishMeaning: 'Especially attractive, stylish, or well done.', thaiMeaning: 'ดูดีมาก หล่อสวย หรือทำออกมาได้ดี', origin: 'A literal “good work” phrase extended to people, looks, and results.', tags: ['compliments'] },
  { slug: 'saep', headword: 'แซ่บ', romanization: 'saep', ipa: 'sɛ̂ːp', englishWord: 'Hot / impressive', englishMeaning: 'Exciting, attractive, sexy, or impressively bold.', thaiMeaning: 'เผ็ดร้อน แซ่บ น่าดึงดูด หรือโดดเด่นมาก', origin: 'Originally an Isan word for spicy or flavorful, adopted nationwide as slang.', tags: ['compliments'] },
  { slug: 'chiap', headword: 'เฉียบ', romanization: 'chiap', ipa: 'tɕʰìːap', englishWord: 'Sharp / cool', englishMeaning: 'Cool, clever, or impressively on point.', thaiMeaning: 'เจ๋ง คม หรือทำได้ดีอย่างมีชั้นเชิง', origin: 'Popularized through Thai entertainment and casual speech.', tags: ['compliments'] },
  { slug: 'krian', headword: 'เกรียน', romanization: 'krian', ipa: 'krīːan', englishWord: 'Troll', englishMeaning: 'An immature, irritating, or deliberately provocative person online.', thaiMeaning: 'คนกวนประสาท ไม่โต หรือชอบยั่วในโลกออนไลน์', origin: 'Associated with schoolboys’ very short hair and aggressive early internet behavior.', tags: ['internet-culture'] },
  { slug: 'thep', headword: 'เทพ', romanization: 'thep', ipa: 'tʰêːp', englishWord: 'Godlike / highly skilled', englishMeaning: 'Exceptionally capable or good at something.', thaiMeaning: 'เก่งมากหรือมีฝีมือระดับสุดยอด', origin: 'The literal word for deity became an exaggerated compliment.', tags: ['compliments'] },
  { slug: 'in', headword: 'อิน', romanization: 'in', ipa: 'ʔīn', englishWord: 'Emotionally invested', englishMeaning: 'Deeply absorbed in or moved by a story, topic, or feeling.', thaiMeaning: 'อินกับเรื่องราวหรือรู้สึกร่วมอย่างมาก', origin: 'Borrowed from English “in,” with a Thai meaning closer to emotionally involved.', tags: ['emotions'] },
  { slug: 'feel', headword: 'ฟีล', romanization: 'feel', ipa: 'fiːl', englishWord: 'Vibe / feeling', englishMeaning: 'A mood, atmosphere, or subjective feeling.', thaiMeaning: 'อารมณ์ บรรยากาศ หรือความรู้สึกโดยรวม', origin: 'Naturalized borrowing from English “feel.”', tags: ['emotions'] },
  { slug: 'khot', headword: 'โคตร', romanization: 'khot', ipa: 'kʰôːt', englishWord: 'Extremely', englishMeaning: 'A very informal intensifier meaning extremely or insanely.', thaiMeaning: 'คำขยายความหมายว่าอย่างมากหรือสุด ๆ ในภาษากันเอง', origin: 'A strong colloquial intensifier; use only in informal contexts.', tags: ['internet-culture'] },
  { slug: 'the-cool', headword: 'เท่', romanization: 'the', ipa: 'tʰêː', englishWord: 'Cool / stylish', englishMeaning: 'Cool, stylish, or admirable.', thaiMeaning: 'ดูดี มีสไตล์ หรือเจ๋ง', origin: 'Common informal compliment used heavily in youth speech.', tags: ['compliments'] },
  { slug: 'jeng', headword: 'เจ๋ง', romanization: 'jeng', ipa: 'tɕěŋ', englishWord: 'Awesome', englishMeaning: 'Cool, clever, or impressive.', thaiMeaning: 'เจ๋ง เก่ง หรือยอดเยี่ยม', origin: 'Established colloquial compliment in Thai youth speech.', tags: ['compliments'] },
  { slug: '555', headword: '555', romanization: 'ha-ha-ha', ipa: 'hâː hâː hâː', englishWord: 'Hahaha / lol', englishMeaning: 'Laughter in Thai texting; more 5s means a bigger laugh.', thaiMeaning: 'เสียงหัวเราะในแชต เพราะเลขห้าอ่านว่า ห้า', origin: 'The Thai pronunciation of 5 is hâa, so 555 reads as ha-ha-ha.', tags: ['chat'] },
  { slug: 'ja', headword: 'จ้า', romanization: 'ja', ipa: 'tɕâː', englishWord: 'Sure / okay', englishMeaning: 'A friendly casual yes, okay, or acknowledgement.', thaiMeaning: 'คำตอบรับแบบกันเอง เช่น ได้เลย โอเค หรือจ้า', origin: 'A casual chat particle often used in place of more formal polite particles.', tags: ['chat'] },
  { slug: 'woei', headword: 'เว้ย', romanization: 'woei', ipa: 'wɤ́ːj', englishWord: 'Hey / dude', englishMeaning: 'An emphatic informal address or sentence ending among peers.', thaiMeaning: 'คำเรียกหรือคำลงท้ายแบบสนิทและไม่เป็นทางการมาก', origin: 'Very informal spoken particle; avoid with elders or strangers.', tags: ['chat'] },
  { slug: 'puang', headword: 'ป่วง', romanization: 'puang', ipa: 'pùːaŋ', englishWord: 'Dazed / down', englishMeaning: 'Feeling mentally off, drained, or emotionally low.', thaiMeaning: 'รู้สึกแปลก ๆ หมดแรง หรือซึมลง', origin: 'Modern colloquial slang with shifting emotional meanings.', tags: ['emotions'] },
  { slug: 'i', headword: 'อี๋', romanization: 'i', ipa: 'ʔǐː', englishWord: 'Ew', englishMeaning: 'An exclamation of disgust or dislike.', thaiMeaning: 'คำอุทานแสดงความรังเกียจหรือไม่ชอบ', origin: 'An expressive sound used in speech and online reactions.', tags: ['chat'] },
  { slug: 'fin', headword: 'ฟิน', romanization: 'fin', ipa: 'fīn', englishWord: 'Blissful', englishMeaning: 'To feel delighted, satisfied, or emotionally fulfilled.', thaiMeaning: 'รู้สึกฟิน มีความสุขหรืออิ่มเอมมาก', origin: 'Borrowed from “fin” and reshaped as a Thai pop-culture expression.', tags: ['emotions'] },
  { slug: 'loep', headword: 'เลิฟ', romanization: 'loep', ipa: 'lɤ̂ːp', englishWord: 'Love', englishMeaning: 'A playful Thai pronunciation used to express love or approval.', thaiMeaning: 'คำเล่นเสียงจาก love ใช้บอกว่ารักหรือชอบมาก', origin: 'English loanword “love” adapted to Thai pronunciation.', tags: ['relationships'] },
  { slug: 'krasae', headword: 'กระแส', romanization: 'krasae', ipa: 'kràʔ.sɛ̌ː', englishWord: 'Trend / buzz', englishMeaning: 'A trend, wave of attention, or current online buzz.', thaiMeaning: 'กระแสหรือสิ่งที่กำลังได้รับความสนใจ', origin: 'A standard word widely used in social-media trend talk.', tags: ['internet-culture'] },
  { slug: 'drama', headword: 'ดราม่า', romanization: 'drama', ipa: 'draː.mâː', englishWord: 'Drama / controversy', englishMeaning: 'Public conflict, controversy, or emotionally charged gossip.', thaiMeaning: 'เรื่องขัดแย้ง ดราม่า หรือประเด็นร้อนบนโซเชียล', origin: 'Borrowed from English “drama.”', tags: ['internet-culture'] },
  { slug: 'content', headword: 'คอนเทนต์', romanization: 'content', ipa: 'kʰɔ̄ːn.tʰēn', englishWord: 'Content', englishMeaning: 'Online media or material created for an audience.', thaiMeaning: 'เนื้อหาสำหรับเผยแพร่ โดยเฉพาะบนโซเชียลมีเดีย', origin: 'Borrowed from English “content” and naturalized in creator culture.', tags: ['internet-culture', 'tech'] },
  { slug: 'jin', headword: 'จิ้น', romanization: 'jin', ipa: 'tɕîn', englishWord: 'To ship', englishMeaning: 'To imagine or support two people as a romantic pairing.', thaiMeaning: 'จินตนาการหรือเชียร์ให้คนสองคนเป็นคู่รักกัน', origin: 'A slang shortening associated with คู่จิ้น and imagined couples.', tags: ['internet-culture'] },
  { slug: 'ueng', headword: 'อึ้ง', romanization: 'ueng', ipa: 'ʔɯ̂ŋ', englishWord: 'Speechless / stunned', englishMeaning: 'So surprised or impressed that one is left speechless.', thaiMeaning: 'ตกใจ ทึ่ง หรือพูดไม่ออกเพราะประหลาดใจ', origin: 'A shortened colloquial form used heavily in reactions.', tags: ['emotions'] },
  { slug: 'tham-rai', headword: 'ทำไร', romanization: 'tham-rai', ipa: 'tʰām raj', englishWord: 'What are you doing?', englishMeaning: 'A casual chat spelling of “what are you doing?”', thaiMeaning: 'รูปย่อแบบแชตของคำถามว่า “ทำอะไรอยู่”', origin: 'A shortened spelling of ทำอะไร used in informal messages.', tags: ['chat'] },
  { slug: 'paep', headword: 'แป๊บ', romanization: 'paep', ipa: 'pɛ́p', englishWord: 'One moment', englishMeaning: 'Wait a moment; just a second.', thaiMeaning: 'รอสักครู่หรือเดี๋ยวเดียว', origin: 'Shortened from แป๊บเดียว in casual speech and chat.', tags: ['chat'] },
  { slug: 'fiao', headword: 'เฟี้ยว', romanization: 'fiao', ipa: 'fíao', englishWord: 'Fierce / stylish', englishMeaning: 'Striking, fashionable, or confidently cool.', thaiMeaning: 'ดูเท่ โฉบเฉี่ยว หรือมีสไตล์มาก', origin: 'Youth slang commonly used for fashion and attitude.', tags: ['compliments'] },
  { slug: 'aom', headword: 'อ่อม', romanization: 'aom', ipa: 'ʔɔ̀ːm', englishWord: 'A flop / underwhelming', englishMeaning: 'Lame, disappointing, or not as good as expected.', thaiMeaning: 'กร่อย แป้ก ไม่ว้าว หรือไม่เป็นไปตามที่คาด', origin: 'A Gen-Z slang re-use of the Isan dish name อ่อม.', tags: ['internet-culture'] },
  { slug: 'tham-thueng', headword: 'ทำถึง', romanization: 'tham-thueng', ipa: 'tʰām tʰɯ̌ŋ', englishWord: 'Go all out', englishMeaning: 'To deliver fully, with commitment and attention to every detail.', thaiMeaning: 'จัดเต็ม ทุ่มสุดตัว และทำได้เกินความคาดหมาย', origin: 'Current social-media praise for work that leaves nothing half-done.', tags: ['compliments'] },
  { slug: 'pai-ya', headword: 'ป้ายยา', romanization: 'pai-ya', ipa: 'pâːj jāː', englishWord: 'Influence someone to buy', englishMeaning: 'To persuade someone to try or buy something through enthusiastic recommendation.', thaiMeaning: 'ชักชวนหรือรีวิวจนคนอื่นอยากซื้อตามหรืออยากลองตาม', origin: 'A social-media metaphor for “applying a dose” of persuasion.', tags: ['internet-culture'] },
  { slug: 'tit-glaem', headword: 'ติดแกลม', romanization: 'tit-glaem', ipa: 'tìt klɛːm', englishWord: 'Living glam', englishMeaning: 'Attached to a glamorous, polished, or luxurious lifestyle.', thaiMeaning: 'ชอบความสวยหรู ใช้ชีวิตแบบดูแพงและจัดเต็ม', origin: 'A social-media blend of ติด and the borrowed “glam.”', tags: ['internet-culture'] },
  { slug: 'rap-jop', headword: 'รับจบ', romanization: 'rap-jop', ipa: 'ráp tɕòp', englishWord: 'Take responsibility', englishMeaning: 'To take on a problem or task and make sure it gets resolved.', thaiMeaning: 'รับผิดชอบงานหรือปัญหาไว้เองเพื่อให้เรื่องจบ', origin: 'A current social-media phrase about taking ownership, even when it was not originally one’s fault.', tags: ['internet-culture'] },
  { slug: 'jueng', headword: 'จึ้ง', romanization: 'jueng', ipa: 'tɕɯ̂ŋ', englishWord: 'Stunning', englishMeaning: 'Strikingly impressive, beautiful, or attention-grabbing.', thaiMeaning: 'โดดเด่นจนตะลึง สวยหรือดีมากจนสะกดสายตา', origin: 'Contemporary youth slang popular in online praise and reaction language.', tags: ['compliments'] },
  { slug: 'tui', headword: 'ตุย', romanization: 'tui', ipa: 'tūj', englishWord: 'Die / be overwhelmed', englishMeaning: 'To “die” jokingly from embarrassment, exhaustion, or an intense reaction.', thaiMeaning: 'พูดเล่นว่า ตายแล้ว หรือหมดสภาพเพราะอารมณ์และเหตุการณ์', origin: 'A playful internet spelling and pronunciation of ตาย.', tags: ['internet-culture'] },
  { slug: 'kaeng', headword: 'แกง', romanization: 'kaeng', ipa: 'kɛ̄ːŋ', englishWord: 'Prank / tease', englishMeaning: 'To trick, prank, or leave someone looking foolish.', thaiMeaning: 'แกล้ง หลอก หรือทำให้คนอื่นเสียหน้าแบบขำ ๆ', origin: 'A slang extension of the food word แกง, used for playful social “cooking.”', tags: ['internet-culture'] },
  { slug: 'shot-feel', headword: 'ช็อตฟีล', romanization: 'shot-feel', ipa: 'tɕʰɔ́t fiːl', englishWord: 'Kill the vibe', englishMeaning: 'To interrupt or ruin someone’s mood or excitement.', thaiMeaning: 'ตัดอารมณ์หรือทำให้บรรยากาศที่กำลังดีสะดุด', origin: 'A Thai-English compound from “short/shot” and “feel,” used for a mood-killing interruption.', tags: ['emotions'] },
]
